### PR TITLE
Fixing datetime 

### PR DESCRIPTION
**Pull request by robkau**
Changed the way datetime is parsed to avoid the format exception being raised every time

For issue https://github.com/jgillick/python-pause/issues/1

Tested on Windows

### CODE REVIEW

**Comment by nbkincaid** [comment]
@robkau @jgillick Are there any actions that need to be taken here?

**Comment by jgillick** [comment]
No, sorry. The last several months have been busy and this totally fell off my radar. I'll look at this tomorrow and merge it in. Thank you for the contribution!

**Comment by jgillick** [comment]
@nbkincaid, @robkau This PR has been merged. Thank you!

**Comment by zed** [comment]
The code for converting a naive datetime object representing the local time to the epoch time looks complicated and it may fail.

It seems it tries to find an analog of `end = time.timestamp()` from Python 3. On Python 2, it would be `end = pytime.mktime(time.timetuple()) + time.microsecond / 1e6`.

Python has no access to the tz database on Windows. `pytz` timezone could be used to provide a portable access:

```
#!/usr/bin/env python
from datetime import datetime
import pytz  # $ pip install pytz
from tzlocal import get_localzone  # $ pip install tzlocal

epoch = datetime(1970, 1, 1, tzinfo=pytz.utc)
local_tz = get_localzone()  # get local timezone
local_time = local_tz.localize(time, is_dst=None) # raise on ambiguous or non-existent time
end = posix_timestamp = (local_time - epoch).total_seconds()
```

See 

- [How do I convert local time to UTC in Python?](http://stackoverflow.com/q/79797/4279)

- [Converting datetime.date to UTC timestamp in Python](http://stackoverflow.com/q/8777753/4279)

- [Getting computer's UTC offset in Python](http://stackoverflow.com/q/3168096/4279)

**Pull request merged**
